### ISSUE TITLE
Unicode error when using --all option

### ISSUE THREAD

**Issue by jdoyle65** [eugenecormier/rudi#18]
Keep getting an error when using the --all option in rudi

```
Traceback (most recent call last):
  File "/var/www/html/rudi/public/rudi/rudi", line 2887, in <module>
    main(args)
  File "/var/www/html/rudi/public/rudi/rudi", line 2771, in main
    IdentifyOtherSevChords(f,g,args.all_chords_inv)
  File "/var/www/html/rudi/public/rudi/rudi", line 2339, in IdentifyOtherSevChords
    g.write('\\relative ' + octave + ' { ' + temp[i] + '_\markup{ ' + font + ' { \with-color #red { ' + key[i] +  ' }} } } ')
UnicodeEncodeError: 'ascii' codec can't encode character '\xf8' in position 75: ordinal not in range(128)
```

**Comment by eugenecormier** [comment]
so is the command exactly this:
rudi --all
?

**Comment by eugenecormier** [comment]
Justin, is it possible that the user env doesn't have unicode support?
check $LANG
it should be something like 'en_US.utf8' or 'en_CA.utf8' and not 'C'
which distro are you using? have you set the locale?

**Comment by jdoyle65** [comment]
Having the issue on both OSX 10.10 and Ubuntu Server 14.04. Although this could be an Apache Server issue. I'm going to see what I can figure out, since it only seems to be happening in the Apache environment.

**Comment by jdoyle65** [comment]
$LANG is set to en_US.utf8 in the environment rudi is being executed in, but still having an issue. I'll keep investigating.

**Comment by jdoyle65** [comment]
Narrowed it down a bit. It's only happening when using the "Other 7th Chords" option.

**Comment by jdoyle65** [comment]
OK got it. Both LANG and LC_ALL needed to be set to en_US.UTF-8 in Apache's start up routine, and rebooted Apache.
